### ISSUE TITLE
Morpheus no longer connects to matrix.org homeserver

### ISSUE THREAD

**Issue by rodneyrod** [baines/morpheus#3]
Could have something to do with the introduction of Cloudflare, as mentioned here:
https://github.com/matrix-org/purple-matrix/issues/72

**Comment by baines** [comment]
Hmm, it seems to work for me with just `export MTX_URL="https://matrix.org"` before running.
I notice the readme.md instructions are outdated though, so I'll fix that.

**Comment by rodneyrod** [comment]
Ahh right, that worked. Had to drop the port number but that seemed to work.
